env: dev
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false
    username: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
